# Nome do simulador bancário
quarkus.application.name=banquarkus

# Conexão nativa via rede Docker apontando para os nomes oficiais dos contêineres
quarkus.mongodb.connection-string=mongodb://app_banquarkus_user:senha123@mongo1:27017,mongo2:27017,mongo3:27017/banquarkus_operacional?replicaSet=banco-rs&authSource=banquarkus_operacional

# Como agora estamos dentro da rede unificada, o Quarkus entende perfeitamente a topologia
quarkus.mongodb.write-concern.w=majority
quarkus.mongodb.read-preference=primary