# Nome do simulador bancário
quarkus.application.name=banquarkus

# Adicionamos o parâmetro localThresholdMS e a diretiva de mapeamento direto para localhost
quarkus.mongodb.connection-string=mongodb://app_banquarkus_user:senha123@127.0.0.1:27017,127.0.0.1:27018,127.0.0.1:27019/banquarkus_operacional?replicaSet=banco-rs&authSource=banquarkus_operacional&loadBalanced=false

# Força o Quarkus a ignorar o roteamento interno do Docker e se prender aos mapeamentos de portas locais
quarkus.mongodb.write-concern.w=majority
quarkus.mongodb.read-preference=primary

